dataset: "csgo_players.csv"

topic: "A multivariate exploration of the CS:GO professional players dataset"

target_audience: >
  Visualization researchers, data science students, and esports analysts
  interested in multivariate performance metrics, role specialization, and
  trade-offs when comparing professional CS:GO players; also suitable as a
  benchmark for auto-charting/recommendation systems.

domain_knowledge: |
  Dataset: HLTV-style professional player statistics.

  Columns:
  - player_id: Player's ID on HLTV
  - nickname: In-game name of the player
  - real_name: Full name of the player
  - age: Player's age
  - country: Country of the player
  - current_team: Current team of the player
  - teams: All teams the player has been part of
  - total_kills: Total kills
  - total_deaths: Total deaths
  - headshot_percentage: % of kills that are headshots
  - damage_per_round: Average damage per round
  - grenade_dmg_per_round: Grenade damage per round
  - maps_played: Total maps played
  - rounds_played: Total rounds played
  - kills_per_death: K/D ratio
  - kills_per_round: Kills per round
  - assists_per_round: Assists per round
  - deaths_per_round: Deaths per round
  - saved_teammates_per_round: Times saving teammates per round
  - saved_by_teammate_per_round: Times saved by teammates per round
  - rounds_with_kills: Rounds in which the player got a kill
  - kill_to_death_diff: Kill-death difference
  - total_opening_kills: Total opening kills
  - total_opening_deaths: Total opening deaths
  - opening_kill_ratio: Opening kill ratio
  - opening_kill_rating: Opening kill rating
  - team_win_percent_after_first_kill: Team win % after player's first kill
  - first_kill_in_won_rounds: % of won rounds with player's first kill
  - 0_kill_rounds: Rounds with 0 kills
  - 1_kill_rounds: Rounds with 1 kill
  - 2_kill_rounds: Rounds with 2 kills
  - 3_kill_rounds: Rounds with 3 kills
  - 4_kill_rounds: Rounds with 4 kills
  - 5_kill_rounds: Rounds with 5 kills
  - rifle_kills: Rifle kills
  - sniper_kills: Sniper kills
  - smg_kills: SMG kills
  - pistol_kills: Pistol kills
  - grenade_kills: Grenade kills
  - other_kills: Other weapon kills
  - rating: Player rating (1.00 average baseline)

  Known quirks & cleaning:
  - Some columns may be integers stored as strings; ensure numeric parsing.
  - Team history may be a semicolon/comma-separated string → split to list.
  - Headshot percentage often stored as "%" → strip symbol, cast to float.
  - Country and team names may contain inconsistent casing → normalize.

  Useful derived features for player analysis:
  - KD_ratio = total_kills / total_deaths
  - Impact score = (opening_kill_rating + kills_per_round + assists_per_round) / 3
  - Clutch_index = (saved_teammates_per_round + first_kill_in_won_rounds) / 2
  - Aggression_flag = (opening_kill_ratio > 1.2) and (kills_per_round > 0.8)
  - Consistency_index = 1 - (0_kill_rounds / rounds_played)
  - Role buckets: entry-fragger, AWPer, support, lurker (based on kill types and assists)

  Example vega-lite filter:
  # Highlight aggressive entry players
  (datum['opening_kill_ratio'] > 1.2 && datum['kills_per_round'] > 0.8) ? 'EntryFragger' : 'Other'

dataset_url: https://raw.githubusercontent.com/the-lord-of-stars/mini-template/dev-yuhan/studio/testing/cs/csgo_players.csv

max_section_number: 8

max_analyses_per_section: 3

dev: false

thread_to_load: thread_20250819_125735